package com.smartypantsltd.nylah.model;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.smartypantsltd.nylah.anim.Rig;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Her model, read from {@code assets/nylah/geo/nylah.geo.json} (generated by
 * {@code tools/model/build_geo.py}, the single definition of her shape).
 *
 * <p>Baked with {@link LayerDefinition#bakeRoot()} directly: no model layer is
 * registered anywhere, so nothing else (resource packs, model-swapping mods)
 * can replace her body. The file comes from our own jar via the classloader,
 * never through the resource manager, for the same reason.</p>
 */
public final class Geo {

    public record Cube(float ox, float oy, float oz, int w, int h, int d, float ix, float iy, float iz, int u, int v) {
    }

    public record Bone(String name, String parent, float[] pivot, float[] rot, List<Cube> cubes, String group) {
    }

    public final int texW;
    public final int texH;
    public final List<Bone> bones;

    private Geo(int texW, int texH, List<Bone> bones) {
        this.texW = texW;
        this.texH = texH;
        this.bones = bones;
    }

    public static Geo load() {
        try (InputStream in = Geo.class.getResourceAsStream("/assets/nylah/geo/nylah.geo.json")) {
            if (in == null) {
                throw new IllegalStateException("nylah.geo.json missing from the jar");
            }
            JsonObject o = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            JsonArray tex = o.getAsJsonArray("texture");
            List<Bone> bones = new ArrayList<>();
            for (JsonElement e : o.getAsJsonArray("bones")) {
                JsonObject b = e.getAsJsonObject();
                List<Cube> cubes = new ArrayList<>();
                for (JsonElement ce : b.getAsJsonArray("cubes")) {
                    JsonObject c = ce.getAsJsonObject();
                    float[] or = floats(c.getAsJsonArray("origin"));
                    JsonArray sz = c.getAsJsonArray("size");
                    float[] inf = floats(c.getAsJsonArray("inflate"));
                    JsonArray uv = c.getAsJsonArray("uv");
                    cubes.add(new Cube(or[0], or[1], or[2], sz.get(0).getAsInt(), sz.get(1).getAsInt(), sz.get(2).getAsInt(),
                            inf[0], inf[1], inf[2], uv.get(0).getAsInt(), uv.get(1).getAsInt()));
                }
                String parent = b.get("parent").isJsonNull() ? null : b.get("parent").getAsString();
                bones.add(new Bone(b.get("name").getAsString(), parent, floats(b.getAsJsonArray("pivot")),
                        floats(b.getAsJsonArray("rot")), cubes, b.get("group").getAsString()));
            }
            return new Geo(tex.get(0).getAsInt(), tex.get(1).getAsInt(), bones);
        } catch (Exception ex) {
            throw new IllegalStateException("Could not read Nylah's model", ex);
        }
    }

    public Rig rig() {
        List<String> names = new ArrayList<>();
        List<String> groups = new ArrayList<>();
        for (Bone b : bones) {
            names.add(b.name());
            groups.add(b.group());
        }
        return new Rig(names, groups);
    }

    /** Build and bake her model. Bones are listed parents-first in the file. */
    public ModelPart bake() {
        MeshDefinition mesh = new MeshDefinition();
        Map<String, PartDefinition> defs = new HashMap<>();
        for (Bone b : bones) {
            PartDefinition parent = b.parent() == null ? mesh.getRoot() : defs.get(b.parent());
            CubeListBuilder cubes = CubeListBuilder.create();
            for (Cube c : b.cubes()) {
                cubes.texOffs(c.u(), c.v()).addBox(c.ox(), c.oy(), c.oz(), c.w(), c.h(), c.d(),
                        new CubeDeformation(c.ix(), c.iy(), c.iz()));
            }
            PartPose pose = PartPose.offsetAndRotation(b.pivot()[0], b.pivot()[1], b.pivot()[2],
                    b.rot()[0], b.rot()[1], b.rot()[2]);
            defs.put(b.name(), parent.addOrReplaceChild(b.name(), cubes, pose));
        }
        return LayerDefinition.create(mesh, texW, texH).bakeRoot();
    }

    private static float[] floats(JsonArray a) {
        float[] f = new float[a.size()];
        for (int i = 0; i < f.length; i++) {
            f[i] = a.get(i).getAsFloat();
        }
        return f;
    }
}
